Require a Copy impl for termcolor's Color
    error[E0382]: borrow of moved value: `color`
      --> src/lib.rs:88:8
       |
    54 | fn do_alert(color: Color, input: TokenStream) -> TokenStream {
       |             ----- move occurs because `color` has type `Color`, which does not implement the `Copy` trait
    ...
    58 |     let color_spec = ColorSpec::new().set_fg(Some(color)).clone();
       |                                                   ----- value moved here
    ...
    88 |     if color == Color::Red && says_error {
       |        ^^^^^ value borrowed here after move
       |
    help: consider cloning the value if the performance cost is acceptable
       |
    58 |     let color_spec = ColorSpec::new().set_fg(Some(color.clone())).clone();
       |                                                        ++++++++